# This is a basic workflow to deploy Serverless to all helpline staging environments

name: Deploy Serverless to all Helpline Staging Environments

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: This is dangerous! Are you sure you want to trigger this workflow? Type "deploy helplines workflow" to continue.
        required: true
      changelog:
        description: Release Changelog - Add a comment about the changes to be included in this release.
        required: true

jobs:
  deploy-aarambh_staging:
    uses: techmatters/serverless/.github/workflows/aarambh_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}      

  deploy-canada_staging: 
    uses: techmatters/serverless/.github/workflows/canada_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}     

  deploy-cl_linealibre_staging: 
    uses: techmatters/serverless/.github/workflows/cl_linealibre_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}     

  deploy-ecpat_philippines_staging: 
    uses: techmatters/serverless/.github/workflows/ecpat_philippines_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}

  deploy-ethiopia_staging: 
    uses: techmatters/serverless/.github/workflows/ethiopia_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}
      
  deploy-flex2_staging: 
    uses: techmatters/serverless/.github/workflows/flex2_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}

  deploy-jamaica_staging: 
    uses: techmatters/serverless/.github/workflows/jamaica_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}

  deploy-malawi_staging: 
    uses: techmatters/serverless/.github/workflows/malawi_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}

  deploy-romania_staging: 
    uses: techmatters/serverless/.github/workflows/romania_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}
      
  deploy-safernet_staging: 
    uses: techmatters/serverless/.github/workflows/safernet_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}
     
  deploy-south_africa_staging: 
    uses: techmatters/serverless/.github/workflows/south_africa_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}
      
  deploy-teguio_colombia_staging: 
    uses: techmatters/serverless/.github/workflows/teguio_colombia_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}
       
  deploy-thailand_staging: 
    uses: techmatters/serverless/.github/workflows/thailand_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}
      
  deploy-uk_staging_III: 
    uses: techmatters/serverless/.github/workflows/uk_staging_III.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}    

  deploy-uk_staging: 
    uses: techmatters/serverless/.github/workflows/uk_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}          

  deploy-hungary_staging:
    uses: techmatters/serverless/.github/workflows/hungary_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}
     
  deploy-zambia_staging: 
    uses: techmatters/serverless/.github/workflows/zambia_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}
 
  deploy-zimbabwe_staging: 
    uses: techmatters/serverless/.github/workflows/zimbabwe_staging.yml@CHI-1259_workflow_to_deploy_serverless_helpline_stg_norerun
    secrets: inherit
    with:
      changelog: ${{ inputs.changelog }}


  # Send Slack notifying success
  send-slack-message:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [deploy-aarambh_staging, deploy-canada_staging, deploy-cl_linealibre_staging, deploy-ecpat_philippines_staging, deploy-ethiopia_staging, deploy-flex2_staging, deploy-jamaica_staging, deploy-malawi_staging, deploy-romania_staging, deploy-safernet_staging, deploy-south_africa_staging, deploy-teguio_colombia_staging, deploy-thailand_staging, deploy-uk_staging_III, deploy-uk_staging, deploy-hungary_staging, deploy-zambia_staging, deploy-zimbabwe_staging]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup credentials to access AWS for parameters
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      # Set any env vars needed from Parameter Store here
      # Slack env
      - name: Set GITHUB_ACTIONS_SLACK_BOT_TOKEN
        uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "GITHUB_ACTIONS_SLACK_BOT_TOKEN"
          env_variable_name: "GITHUB_ACTIONS_SLACK_BOT_TOKEN"
      - name: Set ASELO_DEPLOYS_CHANNEL_ID
        uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "ASELO_DEPLOYS_CHANNEL_ID"
          env_variable_name: "ASELO_DEPLOYS_CHANNEL_ID"

      - name: Slack Aselo channel
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          channel-id: ${{ env.ASELO_DEPLOYS_CHANNEL_ID }}
          slack-message: "`[SERVERLESS PARALLEL DEPLOYMENT]` All Serverless Staging helplines successfully deployed :rocket:."
        env:
          SLACK_BOT_TOKEN: ${{ env.GITHUB_ACTIONS_SLACK_BOT_TOKEN }}